Cloudserver:Cloudserver.cpp
	g++ -std=c++0x -DCPPHTTPLIB_OPENSSLSUPPORT $^ -o $@ -lpthread -lboost_filesystem -lboost_system -lz -lssl -lcrypto
test_ser:test_ser.cpp
	g++ -std=c++0x $^ -o $@ -lpthread
